export const FETCH_PUBLIC_BLOCKS_FULFILLED = 'FETCH_PUBLIC_BLOCKS_FULFILLED';
export const FETCH_PUBLIC_BLOCKS_REJECTED = 'FETCH_PUBLIC_BLOCKS_REJECTED';
export const FETCH_PUBLIC_BLOCKS = 'FETCH_PUBLIC_BLOCKS';

export const FETCH_PUBLIC_TRANSACTIONS_FULFILLED = 'FETCH_PUBLIC_TRANSACTIONS_FULFILLED';
export const FETCH_PUBLIC_TRANSACTIONS_REJECTED = 'FETCH_PUBLIC_TRANSACTIONS_REJECTED';
export const FETCH_PUBLIC_TRANSACTIONS = 'FETCH_PUBLIC_TRANSACTIONS';


export const DOSIGNUP = 'DOSIGNUP';
export const DOLOGIN = 'DOLOGIN';
export const DOLOGOUT = 'DOLOGOUT';
export const DOADMINLOGIN = 'DOADMINLOGIN';
export const DOADMINLOGOUT = 'DOADMINLOGOUT';

//user action
export const FETCH_TRANSACTIONS_FULFILLED = 'FETCH_TRANSACTIONS_FULFILLED';
export const FETCH_TRANSACTIONS_PREVIOUS_FULFILLED = 'FETCH_TRANSACTIONS_PREVIOUS_FULFILLED';

export const FETCH_TRANSACTIONS_REJECTED = 'FETCH_TRANSACTIONS_REJECTED';
export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS';
export const FETCH_BALANCE = 'FETCH_BALANCE';
export const CREATE_TRANSACTION_DONE = 'CREATE_TRANSACTION_DONE';
export const CREATE_TRANSACTION = 'CREATE_TRANSACTION';

//Amin actions
export const FETCH_USERS_BALANCE = 'FETCH_USERS_BALANCE';
export const FETCH_ADMIN_TRANSACTIONS = 'FETCH_ADMIN_TRANSACTIONS';

export const DOLOGINFAIL = 'DOLOGINFAIL';
export const DOADMINLOGINFAIL = 'DOADMINLOGINFAIL';

export const FETCH_INCOME = 'FETCH_INCOME';
export const FETCH_INCOME_FULFILLED = 'FETCH_INCOME_FULFILLED';
