export const FETCH_PUBLIC_TRANSACTIONS_FULFILLED = 'FETCH_PUBLIC_TRANSACTIONS_FULFILLED';
export const FETCH_PUBLIC_TRANSACTIONS_REJECTED = 'FETCH_PUBLIC_TRANSACTIONS_REJECTED';
export const FETCH_PUBLIC_TRANSACTIONS = 'FETCH_PUBLIC_TRANSACTIONS';

export const DOSIGNUP = 'DOSIGNUP';
export const DOLOGIN = 'DOLOGIN';
export const DOLOGOUT = 'DOLOGOUT';
export const DOADMINLOGIN = 'DOADMINLOGIN';
export const DOADMINLOGOUT = 'DOADMINLOGOUT';

export const FETCH_TRANSACTIONS_FULFILLED = 'FETCH_TRANSACTIONS_FULFILLED';
export const FETCH_TRANSACTIONS_REJECTED = 'FETCH_TRANSACTIONS_REJECTED';
export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS';
export const FETCH_BALANCE = 'FETCH_BALANCE';
export const CREATE_TRANSACTION_DONE = 'CREATE_TRANSACTION_DONE';
export const CREATE_TRANSACTION = 'CREATE_TRANSACTION';

export const FETCH_USERS_BALANCE = 'FETCH_USERS_BALANCE';

